### ISSUE TITLE
Deprecated and slated for 2.0 removal

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/mdanalysis#2739]
We have quite a lot of things that are slated for removal in 2.0:

- [x] old density code #2740 
- [x] old hole code #2778 
- [ ] old hbonds code #2746 
- [x] deprecated writers Timestep code #2754 
- [x] progressmeter #2743 

With #2729 I guess we started 2.0 a little bit sooner than anticipated, so I thought I'd check that we are good at doing these removals before we go ahead and start cutting out code?

**Comment by orbeckst** [comment]
Let‘s get started. We‘ll have to figure out a way to do patches for 1.0 but it seems we can just do PRs against master at the moment and treat master as 1.x branch. 

We‘ll figure out a way to backport fixes from develop; I assume that if we do squash merges we get fairly clean diffs that we can cherry-pick or merge into master/1.x.

**Comment by orbeckst** [comment]
Also: remove six!

**Comment by IAlibay** [comment]
@richardjgowers do you mind if I just move hbond_autocorrel to hydrogenbonds for this?

**Comment by richardjgowers** [comment]
Yeah moving it is fine
