### ISSUE TITLE
Release 1.1.0

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/mdanalysis#3159]
Hi all,

Having recently completed 1.0.1, we would like to quickly deliver 1.1.0 ASAP.

This is because:
  1) Windows does not currently work with 1.0.1
  2) There are lots of very useful features sitting in 2.0 which cannot be used (RDKIT, MSD, new helanal, etc...)
  3) Maintaining the 1.x branch is becoming unmanageable - we are now at a point where even py3.6 is getting dropped by upstream packages.

In order to speed things up, we would like to propose a 1 week deadline for code fixes. That is to say, unless there is a good reason not to, after the 21st of March 2021, we will put a code freeze on the current `master` branch and move towards making a release.

After discussions with @richardjgowers and @lilyminium, it is our view that anything that requires longer than that should probably just go into 2.0. Please do speak up if you disagree with this.

As it stands, this is the list of things I believe were earmarked for a final 1.x release:

- [x] TPR indexing #2364 (PR #3153)
- [x] Small boxes in capped_distance #2670
- [x] Warning about upcoming changes to the NCDFWriter's default behaviour (w.r.t. velocity `scale_units`) #2327 PR #3185
- [x] Temp/B factors (I don't think we need warnings for this, but @lilyminium was saying otherwise?) (PR #3161)
- [x] Dealing with hbond_autocorrel (@p-j-smith based on https://github.com/MDAnalysis/mdanalysis/issues/2987#issuecomment-709534851 are we ok to just deprecate or should we just move it?) - @richardjgowers to fix and maybe move instead.
- [x] Warning for changes to the way we get bonds/angles/dihedrals from atomgroups (#2821 and #1264) (PR #3160)
- [x] Fixing Windows builds (#3129) 
- [x] Parmed ts deprecation #3031
- [x] Warning for PDB segid changes #3157 

Is there anything else we need to do? Is this reasonable for everyone?

pinging @MDAnalysis/coredevs

**Comment by lilyminium** [comment]
re: temp/bfactors -- we could warn for the extremely rare case that someone has used ``add_TopologyAttr`` so that both factors are in the same universe, but contain different values, possibly as tags. I'll see if I can make a warning for that case only (that both exist).

**Comment by orbeckst** [comment]
1.1.0 is then really the final MDA 1.x release (short of errors in the package build which might require a patch release).

We'll then stop any support for Python 2.7 & 3.6 (yikes... I am unhappy about how fragile the Python ecosystem is... but that's a different rant) and no more bug fixes for 1.x.

We should publish a requirement file with last known good versions of all deps that make 1.1.0 work.

**Comment by IAlibay** [comment]
With no surprise to anyone, looks like we'll lapse our deadline, but most PRs (except from any NSGrid changes) are open. So unless there's any objections, let's just say it's a code freeze on any new non-critical PRs. If @MDAnalysis/coredevs can concentrate on reviewing what's open we can move with a release as soon as possible.

**Comment by IAlibay** [comment]
Ah seem to have forgotten about `hbond_autocorrel`. @richardjgowers how do you want to deal with it?

**Comment by tylerjereddy** [comment]
> I am unhappy about how fragile the Python ecosystem is

Yeah, the release cadence is 1 major Python version per year now I think.

> We should publish a requirement file with last known good versions of all deps that make 1.1.0 work.

We're working on doing something similar upstream--pinning build- and run-time deps in releases for long-term repeatable builds. For example: https://github.com/scipy/scipy/pull/12862

**Comment by IAlibay** [comment]
What's left to do here?

@richardjgowers - is there anything that needs to be done for NSGrid & hbond autocorrel?

**Comment by IAlibay** [comment]
Release 1.1.1 is now available (we had to skip over 1.1.0 due to a pypi upload issue) 🎉
