### ISSUE TITLE
BLD: PEP518/pyproject.toml todo items

### ISSUE THREAD

**Issue by tylerjereddy** [MDAnalysis/mdanalysis#3526]
Irfan is planning a release soon, and if we do plan to upload a source distribution to PyPI for that release we may want to add a few things to `pyproject.toml` beyond the initial draft in gh-3398. If issues with that file do pop up please ping me directly (`@`) so I see the notification on my phone (a few too many GitHub emails to scan these days..).

- [ ] add a `[project]` section with some useful metadata (can mimic other popular Python projects for this most likely)
  - [ ] name
  - [ ] license
  - [ ] maintainers
  - [ ] requires-python
  - [ ] dependencies (this means "runtime" instead of "buildtime" I think, but just for metadata as I understand it, at least for `pip`)
  - [ ] readme (path to readme file I think)
  - [ ] classifiers (the PyPI homepage for the release will extract a bunch of metadata from here like supported operating systems, and the versions of Python we consider supported)
- [ ] `[project.optional-dependencies]` section
  - [ ] optional testing deps
  - [ ] optional doc building deps
  - [ ] optional development tools/linters, etc.
- [ ] `[project.urls]` for homepage, source repo, etc.

**Comment by IAlibay** [comment]
So how much of this is currently getting picked up from what's in our setup.py? I notice that most of the classifiers are already on our pypi page, is it just a case of moving things from setup.py over to the pyproject.toml?

**Comment by tylerjereddy** [comment]
Yeah, and it looks like some important Python projects are currently opting to keep the copies in both files for now. I actually don't know if there is an order of precedence on the metadata extraction--not exactly an exciting thing to look into, Google might tell us.

I suspect if we're lazy for now the `setup.py` may continue to provide what it did before, but not 100 % sure.

**Comment by IAlibay** [comment]
We can add it all to `pyproject.toml`, keep setup as-is and then see what testpypi does? Worse case scenario we just have to rollback a few things.
