### ISSUE TITLE
Re-implement nuclinfo using `AnalysisBase` style subclasses

### ISSUE THREAD

**Issue by ALescoulie** [MDAnalysis/mdanalysis#3720]
## Is your feature request related to a problem? ##
To complete the overhaul of `nucinfo` we need to rebuild the rest of the functions in the analysis base style in the `nucleicacids` module.

## Describe the solution you'd like ##
Using the `NucPairDist` as a super class rebuild
```python
dists = MinorPairDist([ag1, ag2],[ag3,ag4], U)
dists.run()
```

## TODO
- [x] rebuild `minor_pair`
- [x] rebuild `major_pair`
- [ ] rebuild `phase_cp`
- [ ] rebuild `phase_as`
- [ ] rebuild `tors`

## Additional context ##
In the last update in PR #3611 the I began the process of overhauling nuclinfo, and I would like to finish that process.

**Comment by ALescoulie** [comment]
I'm starting on this and hopefully can get a PR out soon.

**Comment by ALescoulie** [comment]
I  just pushed PR #3735 which add major and minor pair, I'm also working on the torsion angle class, which is a little more involved.

**Comment by orbeckst** [comment]
See #3744 for a discussion on how to represent the typical output data in the `Results` dict.

**Comment by orbeckst** [comment]
Re-open because PR #3735 did not update _all_ classes.
