### ISSUE TITLE
Release 2.5.0

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/mdanalysis#3965]
This is the meta-issue for the 2.5.0 release.

Please comment / update as necessary.

**Target release date:** March 01, 2023

## TODO
- [ ] ..
- [x] Raise NumPy to 1.21 as per NEP29
- [x] Carry out deployment process
- [x] Make 2.5.0 blog post 
- [x] Clean up old dev docs
- [x] Make sure the UserGuide is deployed
