### ISSUE TITLE
docs for MDAnalysis.analysis.waterdynamics are incorrect/not clear

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdanalysis#935]
The docs for [WaterOrientationalRelaxation](http://www.mdanalysis.org/mdanalysis/documentation_pages/analysis/waterdynamics.html#waterorientationalrelaxation) contain code that throws an error (concatenation of an int `i` with a string) and it is not clear what `i` is – it's just set to 0.

For new users it is also not clear what the output represents – it's not defined in the class docs of [MDAnalysis.analysis.waterdynamics.WaterOrientationalRelaxation](http://www.mdanalysis.org/mdanalysis/documentation_pages/analysis/waterdynamics.html#MDAnalysis.analysis.waterdynamics.WaterOrientationalRelaxation).

There are also broken links as under [MeanSquareDisplacement](http://www.mdanalysis.org/mdanalysis/documentation_pages/analysis/waterdynamics.html#meansquaredisplacement).
## Background

For more context see the post [mdanalysis-discussion: water dynamics](https://groups.google.com/d/msg/mdnalysis-discussion/VhdJAwCyH7s/B12UqklYCAAJ)
## TODO
- [ ] check that all code examples run
- [ ] define output for all analysis classes _at least_ in the class docs; you should also briefly explain in the overview docs what the results are and what they mean and perhaps even indicate what to plot.
- [ ] check for broken links

**Comment by alejob** [comment]
Ok, I'll checkt it ;)

**Comment by orbeckst** [comment]
@alejob and @caioss , could you have a look at this, please? We are starting to knock down issues for the 0.16.0 release.

Thanks!

**Comment by alejob** [comment]
Hi, sorry for the late, I'll work on this issue this sunday ;).

Best.
